services:
  www:
    build:
      dockerfile: ./dockerfile.www
    volumes:
      - "./qr_stencil:/app/qr_stencil"
      - "./docker/www/prestart.sh:/app/prestart.sh"
    ports:
      - "80:80"
    environment:
      IS_DEV: true
      RELOAD: true
